table 'Crisped Rice Wafer'
	lineageTag: fb4a84fc-e43e-473f-af17-705ff9ad9058

	column 'Is Crisped Rice Wafer'
		dataType: string
		lineageTag: 1e6fcc9a-d6cb-4285-8928-ef6d589e7c51
		summarizeBy: none
		sourceColumn: Is Crisped Rice Wafer

		annotation SummarizationSetBy = Automatic

	column 'Crisped Rice Wafer_Key'
		dataType: int64
		formatString: 0
		lineageTag: b3856d75-94c2-425a-b493-6c5632cd42f7
		summarizeBy: none
		sourceColumn: Crisped Rice Wafer_Key

		annotation SummarizationSetBy = Automatic

	partition 'Crisped Rice Wafer' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WikwtVtJRMlSK1YlW8ssHMg2UYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Is Crisped Rice Wafer" = _t, Crisped Rice Wafer_Key = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Crisped Rice Wafer_Key", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

