table Hard
	lineageTag: 87e07761-51d1-4ede-a108-9d6c8964bfc5

	column 'Is Hard Candy'
		dataType: string
		lineageTag: f167bba1-b8ae-4dd3-94dd-014405625096
		summarizeBy: none
		sourceColumn: Is Hard Candy

		annotation SummarizationSetBy = Automatic

	column Hard_Key
		dataType: int64
		formatString: 0
		lineageTag: d67f6a4f-57d7-4049-a546-e7eff56780d1
		summarizeBy: none
		sourceColumn: Hard_Key

		annotation SummarizationSetBy = Automatic

	partition Hard = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WikwtVtJRMlSK1YlW8ssHMg2UYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Is Hard Candy" = _t, Hard_Key = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Hard_Key", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

