table Nuts
	lineageTag: b2206be2-5860-4239-ac1b-5715af97efe0

	column 'Contains Nuts'
		dataType: string
		lineageTag: c3e3ca84-d386-4bb2-b21f-706538f53660
		summarizeBy: none
		sourceColumn: Contains Nuts

		annotation SummarizationSetBy = Automatic

	column Nuts_Key
		dataType: int64
		formatString: 0
		lineageTag: 1e9556a4-fece-424b-8674-896d6e97a533
		summarizeBy: none
		sourceColumn: Nuts_Key

		annotation SummarizationSetBy = Automatic

	partition Nuts = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WikwtVtJRMlSK1YlW8ssHMg2UYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Contains Nuts" = _t, Nuts_Key = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Contains Nuts", type text}, {"Nuts_Key", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

