table Packaged
	lineageTag: 384efe93-5586-4882-8d9d-637070389ce3

	column Packaged
		dataType: string
		lineageTag: d137fd3d-863c-4e1b-8d63-6c3e5005c259
		summarizeBy: none
		sourceColumn: Packaged

		annotation SummarizationSetBy = Automatic

	column Packaged_Key
		dataType: int64
		formatString: 0
		lineageTag: 672ddb46-ff14-422f-9f32-5b5fb00e5520
		summarizeBy: none
		sourceColumn: Packaged_Key

		annotation SummarizationSetBy = Automatic

	partition Packaged = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WikwtVtJRMlSK1YlW8ssHMg2UYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"In a Bag" = _t, In a Bag_Key = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"In a Bag_Key", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"In a Bag", "Packaged"}, {"In a Bag_Key", "Packaged_Key"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

